application: vsavevents
version: 1
runtime: python3

handlers:
- url: /_ah/mail/events@vsavevents.appspotmail.com
  script: app.mail
  login: admin

# - url: /users.*
#   script: app.users
#   secure: always
#   login: required

# - url: /(archives|events.*)
#  script: app.events
#  secure: always
#  login: required

- url: /resources
  static_dir: public/resources

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public\/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public\/robots\.txt

inbound_services:
- mail
