application: vsavevents
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/mail/events@vsavevents.appspotmail.com
  script: mail.app
  login: admin

- url: /res
  static_dir: res

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: events.app
  secure: always

inbound_services:
- mail

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: markupsafe
  version: latest
