application: vsavevents
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/mail/events@vsavevents.appspotmail.com
  script: mail.app
  login: admin

- url: /resources
  static_dir: public/resources

- url: /
  script: main.app
  secure: always

- url: /admin.*
  script: admin.app
  secure: always
  login: admin

- url: /(archives|events.*|dutyroster)
  script: events.app
  secure: always
  login: required

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public\/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public\/robots\.txt


inbound_services:
- mail

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: markupsafe
  version: latest
